# Generated by Django 5.1.2 on 2024-10-17 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_order_tracking_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
