# Generated by Django 5.1.2 on 2024-10-19 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profil_picture',
        ),
    ]
